version: "3.8"

services:
  container-watchdog:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: python src/check.py
    volumes:
      - ./config/config.yaml:/app/config/config.yaml:ro
    # Restart the watchdog container automatically if it crashes
    restart: unless-stopped
