# This is an example configuration file for the Container Watchdog script.
# Make sure to replace the placeholders with your actual values.
portainer:
  url: "https://your-portainer-url.com" # Replace with your Portainer URL, if restarting a reverse proxy container portainer uses, use local IP otherwise the restart will fail with error 520 (Web Server Is Returning an Unknown Error)
  api_key: "your_api_key_here" # Replace with your Portainer API key
  endpoint_id: 3 # Replace with your Portainer endpoint ID

container:
  name: "your-container-name"

checks:
  urls:
    - "https://urls-to-check.com"
    - "https://you-can-add-multiple.com"
  # All http status codes listed here will trigger a restart of the container
  error_status_codes:
    - 502
    - 503
    - 504
